config/routes.rb
Rails.application.routes.draw do

  root 'ppes#index'

    resources :ppes do
      collection do
        get :index
        post :upload_usage
        get :confirm_new_ppes
        post :usage
        post :usages_csv_all
        post :daily_csv_all
        post :monthly_usage
        get :change_hour_state
        get :change_daily_state
        delete :destroy
      end
      member do
        get :usages_csv
      end
    end

end

app/models/ppe.rb
class Ppe < ActiveRecord::Base


  attr_accessor :start_date, :end_date

  has_many :hourly_current_usages, dependent: :delete_all
  has_many :area_current_usages, dependent: :delete_all

  def usages area=nil
    usage_type == 'hourly' ? hourly_current_usages.order('date ASC') : (area ? area_current_usages.where(area: area).order('date ASC') : area_current_usages.order('date ASC'))
  end

  def check_areas
    self.update_attribute(:areas, self.usages.map{|u| u.area}.uniq)
  end

  def self.parse_usages json
    usages = JSON.parse(json)
    bad_types = []
    usages.each do |usage|
      case usage['type']
      when 'hourly'
        HourlyCurrentUsage.create(usage)
      when 'area'
        AreaCurrentUsage.create(usage)
      when 'range'
        HourlyCurrentUsage.create_from_range(usage)
      else
        bad_types << usage
      end
    end
  end

  def self.new_ppes content
    usages = JSON.parse(content)
    new_ppes = []
    wrong_type = []
    usages.each do |u|
      new_ppes << u['ppe'] unless Ppe.exists?(code: u['ppe'])
      wrong_type << u['ppe'] if Ppe.exists?(code: u['ppe'], usage_type: u['type']=='area' ? 'hourly' : 'area')
    end
    (new_ppes.present? || wrong_type.present?) ? {new: new_ppes.uniq, wrong: wrong_type.uniq}  : false
  end

  def get_usage start_date, end_date
    return {errors: ["Data początkowa powinna być wcześniejsza niż końcowa"]} if start_date > end_date
    case usage_type
    when 'hourly'

      start_date = (start_date.is_a?(Date) && start_date) || Date.parse(start_date)
      end_date = (end_date.is_a?(Date) && end_date) || Date.parse(end_date)
      #Get usages from rande and sum
      range_usages = self.usages.where("date >= :start_date AND date <= :end_date", :start_date => start_date, :end_date => end_date)
      sum = range_usages.sum(:daily_usage)
      
      #Get dates without usage
      usages_dates = range_usages.map{|u| u.date}
      date_range = (start_date..end_date)
      dates_without_usage = date_range.to_a - usages_dates

      #Sum states and add "-"" if there are empty days 
      states = range_usages.map{|u| u.daily_state}
      states << '-' if dates_without_usage.present?
      states = states.uniq.join(',')

      return {
        usages: range_usages, 
        sum: sum, 
        states: states, 
        start_date: start_date, 
        end_date: end_date, 
        dates_without_usage: dates_without_usage
      }

    when 'area'
      area_usage = {}
      errors = []
      areas.each do |a|
        errors << "Niewystarczająca ilość odczytów dla PPE #{code} dla strefy #{a}" and next if usages(a).count <= 1

        start_date = (start_date.is_a?(Date) && start_date) || Date.parse(start_date)
        end_date = (end_date.is_a?(Date) && end_date) || Date.parse(end_date)

        first_reading, second_reading = self.usages(a).limit(2)
        last_reading, prelast_reading = self.area_current_usages.where(area: a).order('date DESC').limit(2)

        # Check if start_date or end_date is out of readings range
        start_reading = first_reading if first_reading.date >= start_date
        finish_reading = second_reading if first_reading.date >= end_date 

        start_reading = prelast_reading if last_reading.date <= start_date
        finish_reading = last_reading if last_reading.date <= end_date


        unless start_reading
          if start_date == end_date
            start_reading = self.area_current_usages
                                .where("date < :start_date and area = :area", 
                                        :area => a, 
                                        :start_date => start_date
                                      )
                                .order('date DESC')
                                .limit(1)
                                .first
          else
            start_reading = self.area_current_usages
                                .where("date <= :start_date and area = :area", 
                                        :area => a, 
                                        :start_date => start_date
                                      )
                                .order('date DESC')
                                .limit(1)
                                .first
          end
        end
        unless finish_reading
          finish_reading = self.usages.where("date >= :end_date and area = :area", 
                                              :area => a, 
                                              :end_date => end_date)
                                      .limit(1)
                                      .first
        end


        mid_readings = self.area_current_usages
                              .where("date BETWEEN :start_date AND :end_date AND area = :area", 
                                      :area => a, 
                                      :start_date => start_date,
                                      :end_date => end_date
                                    )
                              .order('date DESC')
        
        all_readings = [start_reading, mid_readings, finish_reading].flatten.uniq.sort_by{|a| a.date}

        if(all_readings.length <= 2)
          daily_usage = (all_readings[1].usage - all_readings[0].usage)/(all_readings[0].date..all_readings[1].date).count
          usage = daily_usage*((start_date..end_date).count)
        else
          usage = 0
          (0..(all_readings.length-2)).each do |i|
            date_range = all_readings[i].date..all_readings[i+1].date
            daily_usage = (all_readings[i+1].usage - all_readings[i].usage)/(date_range).count
            # binding.pry
            if(i==0 && start_date < all_readings[i].date)
              usage += (start_date..all_readings[i].date).count*daily_usage
            elsif(i==(all_readings.length-2) && end_date > all_readings[i+1].date)
              usage += (all_readings[i+1].date..end_date).count*daily_usage
            end

            if date_range.cover?(start_date)
              usage += (start_date..all_readings[i+1].date).count*daily_usage
            elsif date_range.cover?(end_date)
              usage += (all_readings[i].date..end_date).count*daily_usage
            else
              usage += (all_readings[i+1].usage - all_readings[i].usage)
            end

          end
        end
        usage_date_range = (start_reading.date..finish_reading.date)
        state = case 
        when start_date>=start_reading.date && end_date<=finish_reading.date
          'R'
        when usage_date_range.cover?(start_date) || usage_date_range.cover?(end_date)
          'S'
        else
          'P'
        end
        area_usage[a] = {
          usages: [start_reading, finish_reading],
          usage: usage,
          state: state,
        }
      end
      return {
        area_usage: area_usage,
        total_usage: area_usage.inject(0){|sum, n| sum + n[1][:usage]},
        total_state: area_usage.map{|au| au[1][:state]}.uniq.join(','),
        start_date: start_date, 
        end_date: end_date,
        errors: errors
      }
    end
  end

  def get_usage_in_csv_row start_date, end_date
    usage = get_usage(start_date, end_date)
    case usage_type
      when 'hourly'
        [self.code, start_date.to_s, end_date.to_s, usage[:sum].round(3).to_s, usage[:states].to_s]  
      when 'area'
        return [self.code, start_date.to_s, end_date.to_s, 'BŁĄD: '+usage[:errors].join(',')] if usage[:errors].present?
        [self.code, start_date.to_s, end_date.to_s, usage[:total_usage].round(3).to_s, usage[:total_state].to_s, usage[:area_usage].keys.join(',').to_s, usage[:area_usage].first[1][:usages][1].date ]
    end
  end

  def get_monthly_usage start_date, end_date
    end_date = Date.parse(end_date+'-01').end_of_month
    start_date = Date.parse(start_date+'-01')
    no_months = (end_date.year * 12 + end_date.month) - (start_date.year * 12 + start_date.month)
    monthly_usages = {}
    (no_months+1).times do |month|
      monthly_usages[("m"+month.to_s).to_sym] = get_usage(start_date+month.months, (start_date+(month+1).months-1.day))
    end
    monthly_usages
  end


  def self.generate_csv ppes, start_date, end_date
    CSV.generate do |csv|
      csv << ['PPE', 'Data Początkowa', 'Data Końcowa', 'Zużycie', 'Status', 'Strefy', 'Ostatni Pomiar']
      ppes.each do |ppe|
        csv << ppe.get_usage_in_csv_row(start_date, end_date)
      end
    end
  end 

  def self.sum_daily_hourly_usages date, area_ppes
    sum_row = [date]
    area_per_hour = 0
    area_ppes.each do |a|
      area_per_hour += (a.get_usage(date,date)[:total_usage]/24).round(3)
    end      
    (0..24).each do |h|
      hourly = HourlyCurrentUsage.where(date: date).sum("CAST(hourly_usage -> '#{h}' ->> 'usage' AS DECIMAL)")
      area_usage = 0
      unless h==24
        area_usage += area_per_hour       
      end
      sum_row << hourly + area_usage
    end
    sum_row
  end

  def self.hourly_report start_date, end_date
    area_ppes = Ppe.where(usage_type: 'area')
    CSV.generate do |csv|
      csv << %w[Data 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
      (Date.parse(start_date)..Date.parse(end_date)).each do |date|
        csv << Ppe.sum_daily_hourly_usages(date, area_ppes)
      end
    end
  end 

end

app/controllers/ppes_controller.rb
class String
  def is_json?
    begin
      !!JSON.parse(self)
    rescue
      false
    end
  end
end

class PpesController < ApplicationController

	def index
		@ppes = Ppe.all
	end

	def upload_usage
		redirect_to :back unless params[:file]
		content = params[:file].read
		redirect_to :back unless content.is_json?
		if @new_ppes = Ppe.new_ppes(content)
			File.open(Rails.root.join('tmp', 'tmp.json'), "wb") { |f| f.write(content) }
			render 'confirm'
		else
			Ppe.parse_usages(content)
			redirect_to ppes_path, notice: 'Odczyty zostały załadowane poprawnie.'
		end
	end

	def confirm_new_ppes
		file = File.open(Rails.root.join('tmp', 'tmp.json'), 'r')
		Ppe.parse_usages(file.read)
		file.close
		File.delete(Rails.root.join('tmp', 'tmp.json'))
		redirect_to ppes_path, notice: 'Odczyty zostały załadowane poprawnie.'
	end

	def usage
		@ppe = Ppe.find(usage_params[:id])
		redirect_to ppes_path, alert: "Wprowadź wszytkie potrzebne atrybuty dla raportu" and return unless @ppe && usage_params[:start_date] && usage_params[:end_date]
		@usages = @ppe.get_usage(usage_params[:start_date], usage_params[:end_date])
		# binding.pry
		redirect_to ppes_path, alert: @usages[:errors].to_s and return if @usages[:errors].present?
	end

	def usages_csv
		@ppe = Ppe.find(params[:id])
		redirect_to ppes_path, alert: "Nie znaleziono podanego PPE" and return unless @ppe && params[:start_date] && params[:end_date]
		csv = Ppe.generate_csv([@ppe], params[:start_date], params[:end_date])
    respond_to do |format|
      format.csv { send_data csv, filename: "zuzycie_#{@ppe.code}_#{Date.today.to_s}.csv" }
    end
	end

  def monthly_usage
    @ppe = Ppe.find(usage_params[:id])
    redirect_to ppes_path, alert: "Wprowadź wszytkie potrzebne atrybuty dla raportu" and return unless @ppe && usage_params[:start_date] && usage_params[:end_date]
    @usages = @ppe.get_monthly_usage(usage_params[:start_date], usage_params[:end_date])
  end

	def usages_csv_all
		@ppes = Ppe.all
		redirect_to ppes_path, alert: "Wprowadź wszytkie potrzebne atrybuty dla raportu" and return unless usage_params[:start_date] && usage_params[:end_date]
		redirect_to ppes_path, alert: "Data początkowa powinna być wcześniejsza niż końcowa" and return if usage_params[:start_date] >= usage_params[:end_date]
		csv = Ppe.generate_csv(@ppes, usage_params[:start_date], usage_params[:end_date])
    respond_to do |format|
      format.csv { send_data csv, filename: "zuzycie_wszystkie_ppe_#{Date.today.to_s}.csv" }
    end
	end

	def daily_csv_all
		@ppes = Ppe.all
		redirect_to ppes_path, alert: "Wprowadź wszytkie potrzebne atrybuty dla raportu" and return unless usage_params[:start_date] && usage_params[:end_date]
		redirect_to ppes_path, alert: "Data początkowa powinna być wcześniejsza niż końcowa" and return if usage_params[:start_date] >= usage_params[:end_date]
		csv = Ppe.hourly_report(usage_params[:start_date], usage_params[:end_date])
    respond_to do |format|
      format.csv { send_data csv, filename: "godzinowe_sumaryczne_#{usage_params[:start_date].to_s}-#{usage_params[:end_date].to_s}.csv" }
    end
	end

	def change_hour_state
		@usage = HourlyCurrentUsage.find(params[:usage_id])
		render 'ajax_error' and return unless @usage
		@usage.change_hour_state(params[:hour], params[:state])
	end

	def change_daily_state
		@usage = HourlyCurrentUsage.find(params[:usage_id])
		render 'ajax_error' and return unless @usage
		@usage.change_daily_state(params[:state])
	end

  def destroy
    @usage = Ppe.find(usage_params[:id])
    @usage.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Usunięto PPE #{@usage.code} wraz z danymi." }
      format.json { head :ok }
    end
  end


	private

	def usage_params
    params.require(:ppe).permit(:id, :start_date, :end_date)
  end

end

app/views/ppes/_area_report.html.haml
= render 'ppes/area_report_summary', { ppe: @ppe, usages: @usages }
= render 'ppes/export_csv_button'

app/views/ppes/_area_report_summary.html.haml
.panel.panel-default
  .panel-body
    %h1 Sumaryczne zużycie
    
    %table.table.table-striped.table-hover
      %tr
        %th PPE
        %td= ppe.code
      %tr
        %th Data początkowa
        %td= usages[:start_date]
      %tr
        %th Data końcowa
        %td= usages[:end_date]
      %tr.success
        %th 
          %h3 Zużycie(kWh)
        %td
          %h3= usages[:total_usage].round(0)
      %tr
        %th Status wyliczenia
        %td= usages[:total_state]


.panel.panel-default
  .panel-body
    - usages[:area_usage].each do |k, v|
      %h1 Strefa #{k}
      %table.table.table-striped.table-hover
        %tr
          %th 
            %h3 Zużycie(kWh)
          %td
            %h3= v[:usage].round(0)
        %tr
          %th Status wylicznia
          %td= v[:state]
        %tr
          %th Odczyty użyte do obliczeń
          %td
            %table.table.table-striped.table-hover
              %tr
                %th Data
                %th Suma(kWh)
                %th Status
              - v[:usages].each do |u|
                %tr
                  %td= u.date
                  %td= u.usage.round(0)
                  %td= u.state

app/views/ppes/_change_daily_state.html.haml
.btn-group
  %a{class: "btn dropdown-toggle #{usage.daily_state=='+' ? 'btn-success' : 'btn-warning' }", "aria-expanded" => "false", "data-target" => "#", "data-toggle" => "dropdown"}
    = usage.daily_state
    %span.caret
    .ripple-wrapper
  %ul.dropdown-menu
    - unless usage.daily_state=='+'
      %li
        =link_to 'Zmień wszytko na +', "/ppes/change_daily_state?usage_id=#{usage.id}&state=%2B", remote: true
    - unless usage.daily_state=='-'
      %li
        =link_to 'Zmień wszytko na -', "/ppes/change_daily_state?usage_id=#{usage.id}&state=-", remote: true
    - unless usage.daily_state=='*'
      %li
        =link_to 'Zmień wszytko na *', "/ppes/change_daily_state?usage_id=#{usage.id}&state=*", remote: true

app/views/ppes/_change_hour_state.html.haml
.btn-group
  %a{class: "btn dropdown-toggle #{state=='+' ? 'btn-success' : 'btn-warning' }", "aria-expanded" => "false", "data-target" => "#", "data-toggle" => "dropdown"}
    = state
    %span.caret
    .ripple-wrapper
  %ul.dropdown-menu
    - unless state=='+'
      %li
        =link_to 'Zmień na +', "/ppes/change_hour_state?usage_id=#{usage.id}&hour=#{h}&state=%2B", remote: true
    - unless state=='-'
      %li
        =link_to 'Zmień na -', "/ppes/change_hour_state?usage_id=#{usage.id}&hour=#{h}&state=-", remote: true
    - unless state=='*'
      %li
        =link_to 'Zmień na *', "/ppes/change_hour_state?usage_id=#{usage.id}&hour=#{h}&state=*", remote: true

app/views/ppes/_export_csv_button.html.haml
%a.btn.btn-danger.btn-fab.btn-raised.mdi-file-file-download{:href => "/ppes/#{@ppe.id}/usages_csv.csv?start_date=#{@usages[:start_date]}&end_date=#{@usages[:end_date]}", "data-original-title" => "Eksport do CSV", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}

app/views/ppes/_hourly_report.html.haml
= render 'ppes/hourly_report_summary', { ppe: @ppe, usages: @usages }

.panel.panel-default
  .panel-body
    %h1 Szczegółowe dane
    %table.table.table-striped.table-hover
      %tr
        %th Data
        %th Suma(kWh)
        %th Status
        %th Godzinowo
      - @usages[:usages].each do |u|
        %tr{id: "usage_#{u.id}"}
          = render 'hourly_usage_details', u: u


= render 'ppes/export_csv_button'

app/views/ppes/_hourly_report_summary.html.haml
.panel.panel-default
  .panel-body
    %h1 Sumaryczne zużycie
    
    %table.table.table-striped.table-hover
      %tr
        %th PPE
        %td= ppe.code
      %tr
        %th Data początkowa
        %td= usages[:start_date]
      %tr
        %th Data końcowa
        %td= usages[:end_date]
      %tr.success
        %th 
          %h3 Zużycie(kWh)
        %td
          %h3= usages[:sum].round(3)
      %tr
        %th Status pomiarów
        %td
          %span{class: "label #{usages[:states]=='+' ? 'label-success' : 'label-warning'}"}
            = usages[:states]
      %tr
        %th Brakujące dni
        %td
          -if usages[:dates_without_usage].present?
            Brakuje odczytów z następujących dni: 
            %br
            -usages[:dates_without_usage].each do |d|
              %span.label.label-warning
                = d
          -else
            %span.label.label-success
              Wszystkie odczyty

app/views/ppes/_hourly_usage_details.html.haml
%td= u.date
%td= u.daily_usage.round(3)
%td= render('change_daily_state', usage: u)
%td
  %table.table.table-striped
    %thead
      %tr
        - 8.times do |h|
          %th=h
    %tr
      -Hash[u.hourly_usage.to_a[0..7]].each do |hour, usage|
        %td= "#{usage['usage']} (#{render('change_hour_state', state: usage['state'], h: hour, usage: u)})".html_safe
    %thead
      %tr
        - 8.times do |h|
          %th=(h+8)
    %tr
      -Hash[u.hourly_usage.to_a[8..15]].each do |hour, usage|
        %td= "#{usage['usage']} (#{render('change_hour_state', state: usage['state'], h: hour, usage: u)})".html_safe
    %thead
      %tr
        - 8.times do |h|
          %th=(h+16)              
    %tr
      -Hash[u.hourly_usage.to_a[16..23]].each do |hour, usage|
        %td= "#{usage['usage']} (#{render('change_hour_state', state: usage['state'], h: hour, usage: u)})".html_safe
    %thead
      %tr
        %td 24*
    %tr
      -Hash[u.hourly_usage.to_a[24]].each do |hour, usage|
        %td= "#{usage['usage']} (#{render('change_hour_state', state: usage['state'], h: hour, usage: u)})".html_safe

app/views/ppes/change_daily_state.js.haml
$('#usage_#{@usage.id}').html('#{j render('ppes/hourly_usage_details', u: @usage)}');
toastr.success('Zmieniono statusy dla całego dnia');

app/views/ppes/change_hour_state.js.haml
$('#usage_#{@usage.id}').html('#{j render('ppes/hourly_usage_details', u: @usage)}');
toastr.success('Zmieniono status dla godziny');

app/views/ppes/confirm.html.haml
.panel.panel-default
  .panel-body
    - if @new_ppes[:new].present?
      %h1 
        W pliku wykryto nowe PPE

      %ul
        - @new_ppes[:new].each do |ppe|
          %li= ppe
    
    - if @new_ppes[:wrong].present?
      %h1 
        W pliku wykryto próbe wczytania złego typu odczytów

      %ul
        - @new_ppes[:wrong].each do |ppe|
          %li= ppe

    .text-right
      = link_to "Anuluj", ppes_path, class: 'btn btn-flat btn-danger'
      = link_to "Potwierdź", confirm_new_ppes_ppes_path , class: 'btn btn-primary'

app/views/ppes/monthly_usage.html.haml
- @usages.each do |k, monthly_usage|
  = render "ppes/#{@ppe.usage_type}_report_summary", {ppe: @ppe, usages: monthly_usage}

app/views/ppes/usage.html.haml
- if @ppe.usage_type == 'hourly'
  = render 'ppes/hourly_report'
-else
  = render 'ppes/area_report' 